const Head = () => {
  return (
    <>
      <title>Anh Tuấn - Vũ Quỳnh | Save the date</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta data-n-head="ssr" data-hid="og:title" property="og:title" content="Anh Tuấn - Vũ Quỳnh | 12.08.23"></meta>
      <meta data-n-head="ssr" data-hid="description" property="og:description" content="Thân mời"></meta>
      <meta data-n-head="ssr" data-hid="og:description" property="og:description" content="Thân mời"></meta>
      <meta data-n-head="ssr" data-hid="og:image" property="og:image" content="https://firebasestorage.googleapis.com/v0/b/portfolio-firecms.appspot.com/o/thumbnail.jpg?alt=media"></meta>
      <link
        href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100;200;300;400;500&amp;display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Oooh+Baby&display=swap"
        rel="stylesheet"
      />
    </>
  )
}

export default Head
