const Head = () => {
  return (
    <>
      <title>Anh Tuấn - Vũ Quỳnh | Save the date</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100;200;300;400;500&amp;display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Oooh+Baby&display=swap"
        rel="stylesheet"
      />
    </>
  )
}

export default Head
